name: Update PUN Data

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        env:
          SGR_USERNAME: ${{ secrets.SGR_USERNAME }}
          SGR_PASSWORD: ${{ secrets.SGR_PASSWORD }}
          SGR_BASE_URL: ${{ secrets.SGR_BASE_URL }}
        run: node scrape-pun.js
      
      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add pun.json

          git diff --cached --quiet || git commit -m "Daily PUN update"

          git push
